import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins", // Optional: CSS variable for dynamic theming
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add the weights you need
});

export const metadata: Metadata = {
  title: "JMY Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
